export const cabildo = [
  {
    id: 'presidente',
    tipo: 'presidente',
    orden: 1,
    nombre: 'C. Francisco Flores Robles',
    cargo: 'Presidente Municipal',
    administracion: '2024-2027',
    suplente: null,
    comisiones: [],
    bio: 'Presidente Municipal Constitucional del Gobierno Municipal de Arivechi, Sonora.',
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'sindica',
    tipo: 'sindica',
    orden: 2,
    nombre: 'Alba Luz Ocaña Montenegro',
    cargo: 'Síndica Municipal',
    administracion: '2024-2027',
    suplente: 'Diana Cecilia Porchas Lara',
    comisiones: [],
    bio: 'Síndica Municipal del Gobierno Municipal de Arivechi.',
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'regidor-1',
    tipo: 'regidor',
    orden: 3,
    nombre: 'Manuel de Jesús Osorio Quintana',
    cargo: 'Regidor Propietario',
    administracion: '2024-2027',
    suplente: 'Manuel Martínez Ochoa',
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'regidor-2',
    tipo: 'regidor',
    orden: 4,
    nombre: 'Itzel Banessa Bermúdez Tepuri',
    cargo: 'Regidora Propietaria',
    administracion: '2024-2027',
    suplente: 'Alexia Itzayana Trujillo Amaya',
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'regidor-3',
    tipo: 'regidor',
    orden: 5,
    nombre: 'María Patricia Duarte Ramírez',
    cargo: 'Regidora Propietaria',
    administracion: '2024-2027',
    suplente: 'Dyna Patricia García Márquez',
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'regidor-4',
    tipo: 'regidor',
    orden: 6,
    nombre: 'Abel Francisco Robles Gámez',
    cargo: 'Regidor Propietario',
    administracion: '2024-2027',
    suplente: 'Héctor Fernando Barba Martínez',
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'regidor-5',
    tipo: 'regidor',
    orden: 7,
    nombre: 'Faviola Sierra Rodríguez',
    cargo: 'Regidora Propietaria',
    administracion: '2024-2027',
    suplente: 'Nereida Sujey Robles García',
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'dif',
    tipo: 'dif',
    orden: 8,
    nombre: 'Lic. Carla María Monge García',
    cargo: 'Presidenta del DIF Municipal',
    administracion: '2024-2027',
    suplente: null,
    comisiones: [],
    bio: 'Presidenta del Sistema para el Desarrollo Integral de la Familia (DIF) Municipal.',
    email: null,
    telefono: null,
    foto: null,
  },
];

export const presidente = cabildo.find((m) => m.tipo === 'presidente');
export const sindica = cabildo.find((m) => m.tipo === 'sindica');
export const regidores = cabildo.filter((m) => m.tipo === 'regidor');
export const dif = cabildo.find((m) => m.tipo === 'dif');

export default cabildo;
