// Cabildo y gabinete de Baviácora — administración 2024-2027.
// Datos confirmados desde el sitio oficial (baviacora.gob.mx, categorías Cabildo
// y "Gabinete y dependencias", nov-2025). NO inventar nombres: lo no confirmado
// se queda fuera (regidores 4-6 no publicados, DIF sin titular confirmado).
export const cabildo = [
  {
    id: 'presidente',
    tipo: 'presidente',
    orden: 1,
    nombre: 'Jesús Francisco Martín Miranda Villa',
    cargo: 'Presidente Municipal',
    administracion: '2024-2027',
    suplente: null,
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'sindica',
    tipo: 'sindica',
    orden: 2,
    nombre: 'Sandra Amada Juárez Romero',
    cargo: 'Síndica Municipal',
    administracion: '2024-2027',
    suplente: null,
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'regidor-1',
    tipo: 'regidor',
    orden: 3,
    nombre: 'Francisco Antonio Villa Alday',
    cargo: 'Regidor',
    administracion: '2024-2027',
    suplente: null,
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'regidor-2',
    tipo: 'regidor',
    orden: 4,
    nombre: 'Francisca Edith Espinoza Montero',
    cargo: 'Regidora',
    administracion: '2024-2027',
    suplente: null,
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'regidor-3',
    tipo: 'regidor',
    orden: 5,
    // El sitio oficial escribe el apellido como "SANEZ CORDOVA"; probable forma
    // correcta "Sáenz Córdova". <<VERIFICAR ortografía oficial>>
    nombre: 'Francisca Aidee Sáenz Córdova',
    cargo: 'Regidora',
    administracion: '2024-2027',
    suplente: null,
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'secretario',
    tipo: 'secretario',
    orden: 6,
    nombre: 'José Luis Félix Barceló',
    cargo: 'Secretario Municipal',
    administracion: '2024-2027',
    suplente: null,
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'tesorera',
    tipo: 'tesorero',
    orden: 7,
    nombre: 'María Esmeralda Miranda Ahumada',
    cargo: 'Tesorera',
    administracion: '2024-2027',
    suplente: null,
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
  {
    id: 'contralor',
    tipo: 'contralor',
    orden: 8,
    nombre: 'Francisca Elizabeth Corella García',
    cargo: 'Órgano Interno de Control',
    administracion: '2024-2027',
    suplente: null,
    comisiones: [],
    bio: null,
    email: null,
    telefono: null,
    foto: null,
  },
];

export const presidente = cabildo.find((m) => m.tipo === 'presidente');
export const sindica = cabildo.find((m) => m.tipo === 'sindica');
export const regidores = cabildo.filter((m) => m.tipo === 'regidor');
export const dif = cabildo.find((m) => m.tipo === 'dif'); // sin titular confirmado → undefined

export default cabildo;
